services:
  # Servicio de Base de Datos
  mysql_db:
    image: mysql:8.0
    container_name: skilllink_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: skilllink_db
    ports:
      - "3306:3306"
    volumes:
      - ./SkillLink.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql

  # Servicio de Autenticación
  auth-service:
    build:
      context: ./services/auth-service/Auth-Service
      dockerfile: Dockerfile
    container_name: auth_service
    ports:
      - "5001:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=skilllink_db;Port=3306;Database=skilllink_db;User=root;Password=root;
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      - mysql_db

  # Servicio de Usuarios
  user-service:
    build: ./services/user-service
    ports:
      - "3001:3000"
    depends_on:
      - mysql_db

  # Gestor de Servicios
  service-manager:
    build: ./services/service-manager
    ports:
      - "3002:3000"
    depends_on:
      - mysql_db

  # Servicio de Proveedores
  provider-service:
    build: ./services/provider-service
    ports:
      - "3003:3000"
    environment:
      - DB_HOST=mysql_db
      - PORT=3000
    depends_on:
      - mysql_db

  # Servicio de Chat
  chat-service:
    build: ./services/chat-service
    ports:
      - "3004:3000"
    environment:
      - PORT=3000

  # Servicio de Pagos
  payment-service:
    build: ./services/payment-service
    ports:
      - "3005:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_db:3306/skilllink_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - mysql_db

  # API Gateway 
  api-gateway:
    build: ./services/api-gateway
    container_name: api_gateway
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - AUTH_SERVICE_URL=http://auth-service:8080
      - USER_SERVICE_URL=http://user-service:3000
      - SERVICE_MANAGER_URL=http://service-manager:3000
      - PROVIDER_SERVICE_URL=http://provider-service:3000
      - CHAT_SERVICE_URL=http://chat-service:3000
      - PAYMENT_SERVICE_URL=http://payment-service:8081
    depends_on:
      - auth-service
      - user-service
      - service-manager
      - provider-service
      - chat-service

# Servicio de notificaciones
  notification-service:
    build: ./services/notification-service
    container_name: notification_service
    ports:
      - "3006:3006"
    depends_on:
      - mysql_db
    environment:
      DB_HOST: mysql_db
      PORT: 3006


volumes:
  mysql_data: