# Puerto del servicio
server.port=8081

# Configuración de la Base de Datos SkillLink
spring.datasource.url=jdbc:mysql://localhost:3306/skilllink_db?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password= root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuration PayPal Sandbox
paypal.client.id=AameZXzwVw5REFvduALuH5wMuNwWSpMKu3F6vucjKEUZ8YhBlb3nJnLjUOSoS_JNdkeCRjQSZjSoY_gu
paypal.client.secret=EKCGpAtarC7WuL0pW1aB4uZrkh8zi21nWG39GzjvAhxRzBZO1eogNArCxZVAmCLWMgbHWGvLPMRq1aBG
paypal.mode=sandbox